name: nevada
description: A new Flutter project.

version: 1.3.0+11

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  ## Flutter SDK
  flutter:
    sdk: flutter

  ## Online
  audioplayers: ^0.14.0
  cached_network_image: ^2.0.0
  cloud_firestore: ^0.13.0+1
  connectivity: ^0.4.6+2
  dio: ^3.0.8
  flutter_web_browser: ^0.11.0
  weather: ^0.9.5
  flutter_mailer: ^0.4.1+2
  
  ## Widgets
  auto_size_text: ^2.1.0
  big_tip: ^1.0.0
  expand_widget: ^0.2.0+2
  row_collection: ^0.2.4
  sliver_fab: ^1.0.0
  flutter_parsed_text: ^1.2.3
  flutter_youtube: ^2.0.0

  ## Tools
  intl: ^0.16.1
  open_file: ^3.0.1
  package_info: ^0.4.0+13
  password: ^1.0.0
  provider: ^4.0.2
  shared_preferences: ^0.5.6+1

flutter:
  assets:
    - assets/tests/
    - assets/images/cateterismo_examples/
    - assets/images/ecg_examples/CIA/
    - assets/images/ecg_examples/Derrame_Pericardico/
    - assets/images/ecg_examples/Disfuncion_Severa_VI/
    - assets/images/ecg_examples/Ecocardio_Normal/
    - assets/images/ecg_examples/Endocarditis/
    - assets/images/ecg_examples/Insuficiencia_Aortica/
    - assets/images/ecg_examples/Mixoma_Auricular/
    - assets/images/ecg_examples/Prolapso_Mitral/
    - assets/images/electro_examples/
    - assets/images/inspeccion_examples/
    - assets/images/extras/
    - assets/audios/

  uses-material-design: true
